// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// This file stores all the Firebase configuration options for each platform.
/// Flutter uses this to know how to connect your app to Firebase.
///
/// Example:
/// ```dart
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  // This getter returns the correct Firebase options depending on
  // whether the app is running on Web, Android, iOS, etc.
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      // If running on web, use the web config
      return web;
    }
    // Check which platform the app is running on
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        // Use Android Firebase configuration
        return android;
      // The rest of these platforms don't have Firebase configs set up yet
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Firebase configuration for Web apps
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbX7k64XqzT0fYfLHkQqt7V9IErkwyvEM',
    appId: '1:652130115630:web:7ecf70cd24e1d1ae79ffbf',
    messagingSenderId: '652130115630',
    projectId: 'todolist-2-42de3',
    authDomain: 'todolist-2-42de3.firebaseapp.com',
    storageBucket: 'todolist-2-42de3.firebasestorage.app',
  );

  // Firebase configuration for Android apps
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoyMTaVMhPLQk0XSUnLdC4qiCxBLnAHTg',
    appId: '1:652130115630:android:139cbb8e2e5e51c879ffbf',
    messagingSenderId: '652130115630',
    projectId: 'todolist-2-42de3',
    storageBucket: 'todolist-2-42de3.firebasestorage.app',
  );
}
